### ISSUE TITLE
pdf() for multivariateNormal distribution doesn't provide probabilities for continuous random variable

### ISSUE THREAD

**Issue by scigeek72** [Michedev/VAE_anomaly_detection#5]
Hello,
I am taking a keen interest in your implementation of reconstruction probability as I myself is trying to solve a similar issue. 
While looking at your code, on line 195, you tried to compute the probability of a reconstruction by using .pdf(). I think that should be .cdf() function. For continuous distribution, pdf doesn't provide probability of an event. Hence it's values could be > 1. For example, for this distribution, N(0,1e-4), a pdf(0) would provide a value of 3989. (approx). On the other hand, cdf(0) is .5 which is what is expected if you do the calculation by hand. cdf(x) provides the answer to the question p(X <=x). This is almost impossible to derive a point estimate of probability in the continuous case. You can do cdf(x) ~ cdf(x-\epsilon) + pdf(x)*\epsilon where \eplison is infinitesimally small.

**Comment by severous** [comment]
Hi @Michedev @scigeek72  I  am alao interested in this issue. I would like to know how to get resconstruction probability which is less than 1.

**Comment by Michedev** [comment]
Thank you for your interest! I was very busy in this period but now I will give a look!

**Comment by Michedev** [comment]
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.multivariate_normal.html

For continuous distribution, .pdf gives the probability of encountering X given mu and sigma assuming Normal distribution, therefore it must have maximum probability when mu=x. In my opinion, the use of the term "event" is wrong for this case since we are treating continuous distributions, not discrete ones.
As you said, cumulative distribution gives P(X<=x) so any extreme value at the right of the mean has a very high probability but this is wrong: for instance, assuming Normal Standard distribution, P(X=3) = 0.004 then it would be an anomaly but if we use cumulative distribution P(X<=3) = 0.9987 then is not anymore an anomaly

**Comment by severous** [comment]
thanks for your help. I understood it :).



At 2021-05-02 02:30:42, "Michedev" ***@***.***> wrote:

https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.multivariate_normal.html

For continuous distribution, .pdf gives the probability of encountering X given mu and sigma assuming Normal distribution, therefore it must have maximum probability when mu=x. In my opinion, the use of the term "event" is wrong for this case since we are treating continuous distributions, not discrete ones.
As you said, cumulative distribution gives P(X<=x) so any extreme value at the right of the mean has a very high probability but this is wrong: for instance, assuming Normal Standard distribution, P(X=3) = 0.004 then it would be an anomaly but if we use cumulative distribution P(X<=3) = 0.9987 then is not anymore an anomaly
